[general]
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true

[window.padding]
x = 5
y = 5

[mouse]
